use crate::lockfile::LockFile;

/// Serialize a `LockFile` to the `project.lock` format.
pub fn write_lock_file(lock: &LockFile) -> String {
    let mut lines = Vec::new();

    lines.push("// Auto-generated by WFL. Do not edit.".to_string());
    lines.push("// Records exact versions for reproducible builds.".to_string());

    for pkg in &lock.packages {
        lines.push(String::new());
        lines.push(format!("package {}", pkg.name));
        lines.push(format!("  version is {}", pkg.version));
        if !pkg.checksum.is_empty() {
            lines.push(format!("  checksum is {}", pkg.checksum));
        }
        for dep in &pkg.dependencies {
            lines.push(format!("  requires {} {}", dep.name, dep.version));
        }
    }

    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lockfile::{LockedDependency, LockedPackage};
    use crate::manifest::version::Version;

    #[test]
    fn test_write_lock_file() {
        let lock = LockFile {
            packages: vec![
                LockedPackage {
                    name: "http-client".to_string(),
                    version: Version::new(26, 1, Some(3)),
                    checksum: "wflhash:a3f8b2c9d4e5f6a7".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "json-parser".to_string(),
                    version: Version::new(25, 12, Some(8)),
                    checksum: "wflhash:b4c5d6e7f8a9b0c1".to_string(),
                    dependencies: vec![LockedDependency {
                        name: "text-utils".to_string(),
                        version: Version::new(25, 11, Some(2)),
                    }],
                },
            ],
        };

        let output = write_lock_file(&lock);
        assert!(output.contains("package http-client"));
        assert!(output.contains("  version is 26.1.3"));
        assert!(output.contains("  requires text-utils 25.11.2"));
    }

    #[test]
    fn test_roundtrip() {
        let lock = LockFile {
            packages: vec![LockedPackage {
                name: "test-pkg".to_string(),
                version: Version::new(26, 2, Some(1)),
                checksum: "wflhash:abc123".to_string(),
                dependencies: vec![],
            }],
        };

        let output = write_lock_file(&lock);
        let parsed = crate::lockfile::parser::parse_lock_file(&output).unwrap();
        assert_eq!(parsed.packages.len(), 1);
        assert_eq!(parsed.packages[0].name, "test-pkg");
        assert_eq!(parsed.packages[0].version.to_string(), "26.2.1");
    }
}
