[package]
name = "wfl-project"
version = "0.1.0"
edition = "2024"
description = "WebFirst Language project with integrated editor"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
wfl_core = "0.1.0"  # WebFirst Language core library

[workspace]
members = ["."]
