name: Auto Format

on:
  push:
    branches: [ main ]

jobs:
  format-on-failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Apply rustfmt
        run: cargo fmt --all
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format on CI failure"
