name: Memory Leak Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  memory-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build with dhat profiling
      run: |
        cargo build --release --features dhat-heap
        cargo test --release --features dhat-heap --no-run
    - name: Run memory test
      run: |
        DHAT_PROFILE=1 cargo test --features dhat-heap test_log_message_memory_usage -- --nocapture
    - name: Verify memory usage
      run: |
        # Parse dhat-heap.json to extract max_bytes value with null-check
        MAX_BYTES=$(python -c "import json; data = json.load(open('dhat-heap.json')); print(data.get('max_bytes', 0))")
        if [ $MAX_BYTES -lt 15728640 ]; then
          echo "Memory usage within acceptable limits: $MAX_BYTES bytes"
        else
          echo "Memory usage exceeds limits: $MAX_BYTES bytes"
          exit 1
        fi
